version: '2'
services:
    tandem6portal-app:
        image: tandem6portal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tandem6portal-mysql:3306/tandem6portal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tandem6portal-mysql:
        extends:
            file: mysql.yml
            service: tandem6portal-mysql
